version: '3'

services:

  app:
    container_name: app
    image: node:15
    entrypoint: docker-entrypoint.sh
    volumes:
      - ./node:/usr/src/app:rw
    command: sh -c "npm install && node index.js"
    expose:
      - 3000
    networks:
      - node-network
    tty: true
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "ss -tulpn | grep -q 'users:((\"node\",pid'"]
      interval: 5s
      timeout: 30s
      retries: 5

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    container_name: nodenginx
    restart: always
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      app:        
        condition: service_healthy

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysqldb:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATEBASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  node-network:
    driver: bridge